# Generated by Django 6.0.1 on 2026-02-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentlog_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_transac_8e9d99_idx',
            old_name='payments_pa_transac_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_pa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_5bbfc5_idx',
            old_name='payments_pa_user_cr_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
