# Generated by Django 6.0.1 on 2026-01-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_rename_name_brand_band_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'color', 'size')},
        ),
    ]
