# Generated by Django 6.0.1 on 2026-02-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_brand_band_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='band_name',
            new_name='brand_name',
        ),
    ]
