# Generated by Django 6.0.1 on 2026-05-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
